server:
  port: 8763
spring:
  application:
    name: SMARTCAFETERIA-FACEAPI
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://check.monsters1228.cc:3308/smartcafeteria?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    initial-size: 20
    min-idle: 10
    max-active: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# spring cloud eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册地址
    fetch-registry: true
    instance:
      prefer-ip-address: true
    register-with-eureka: true
